package com.liu.haoahstu.auto.mapper;

import com.liu.haoahstu.auto.dao.TBorrow;
import com.liu.haoahstu.auto.dao.TBorrowExample;
import com.liu.haoahstu.auto.dao.TBorrowKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBorrowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    long countByExample(TBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    int deleteByExample(TBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    int deleteByPrimaryKey(TBorrowKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    int insert(TBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    int insertSelective(TBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    List<TBorrow> selectByExample(TBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    TBorrow selectByPrimaryKey(TBorrowKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") TBorrow record, @Param("example") TBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    int updateByExample(@Param("record") TBorrow record, @Param("example") TBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    int updateByPrimaryKeySelective(TBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    int updateByPrimaryKey(TBorrow record);
}