package com.liu.haoahstu.auto.dao;

public class TBookKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_id
     *
     * @mbg.generated Mon Apr 22 22:28:02 GMT+08:00 2019
     */
    private String bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_id
     *
     * @return the value of t_book.book_id
     *
     * @mbg.generated Mon Apr 22 22:28:02 GMT+08:00 2019
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_id
     *
     * @param bookId the value for t_book.book_id
     *
     * @mbg.generated Mon Apr 22 22:28:02 GMT+08:00 2019
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }
}