package com.liu.haoahstu.auto.dao;

public class TBorrowKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrow.book_id
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    private String bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrow.user_id
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrow.book_id
     *
     * @return the value of t_borrow.book_id
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrow.book_id
     *
     * @param bookId the value for t_borrow.book_id
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrow.user_id
     *
     * @return the value of t_borrow.user_id
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrow.user_id
     *
     * @param userId the value for t_borrow.user_id
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}