package com.liu.haoahstu.auto.dao;

import java.util.Date;

public class TBorrow extends TBorrowKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrow.create_date
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrow.end_date
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrow.create_date
     *
     * @return the value of t_borrow.create_date
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrow.create_date
     *
     * @param createDate the value for t_borrow.create_date
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrow.end_date
     *
     * @return the value of t_borrow.end_date
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrow.end_date
     *
     * @param endDate the value for t_borrow.end_date
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}