package com.liu.haoahstu.auto.dao;

public class TLoginKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login.id
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login.id
     *
     * @return the value of t_login.id
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login.id
     *
     * @param id the value for t_login.id
     *
     * @mbg.generated Tue Apr 16 13:34:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}